services:
  monitor:
    build: .
    container_name: monitor-consoles
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=America/Sao_Paulo
    shm_size: "1gb"
    volumes:
      - ./data:/app/data
